site_name: ETL Framework
theme:
  name: material

nav:
  - Início: index.md
  - Instalação: setup/installation.md
  - Arquitetura: setup/architecture.md
  - Guias:
      - Criar Conectores: guides/new-connector.md
      - Pipeline Runner: guides/pipeline.md
  - Próximos Passos: next-steps.md

markdown_extensions:
  - codehilite
  - admonition
